# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='unknown', max_length=32),
            preserve_default=False,
        ),
    ]
